---
- name: Create development virtual hosts
  template: src=../templates/dev_vhost.conf.j2 dest=/etc/apache2/sites-available/{{item['host']}}.conf
  with_items: virtual_hosts
  notify: Restart apache

- name: Setup apache_logs directory
  file: path=/home/vagrant/apache_logs state=directory

- name: Ensure dev virtual host access logs are present
  copy: content= dest=/home/vagrant/apache_logs/{{item['host']}}-access.log mode=0755 force=no
  with_items: virtual_hosts

- name: Ensure dev virtual host error logs are present
  copy: content= dest=/home/vagrant/apache_logs/{{item['host']}}-error.log mode=0755 force=no
  with_items: virtual_hosts

- name: Link up dev virtual hosts with vagrant share
  file: src=/home/vagrant/web/{{item['directory']}} dest=/var/www/{{item['directory']}} state=link
  with_items: virtual_hosts
  tags:
    - vagrant

- name: Enable virtual hosts
  file:
    src: /etc/apache2/sites-available/{{ item['host'] }}.conf
    dest: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: link
  with_items: virtual_hosts
  notify: Restart apache
