---
- name: Ensure mysql packages are installed
  apt: name={{item}} state=installed
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  tags: mysql

- name: Ensure mysql is running
  service: name=mysql state=started
  tags: mysql

- name: Setup mysql config
  template: src=../templates/my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: Restart mysql
  tags: mysql

- name: Create mysql users
  mysql_user: name={{item['user']}} password={{item['password']}} priv=*.*:ALL state=present
  with_items: mysql_users
  tags: mysql

- name: Create development databases
  mysql_db: name={{ item['name'] }} state=present
  with_items: mysql_databases
  tags: mysql
